import getSlug from "./getSlug";

export interface ImageSrc {
  src: string;
  alt: string;
}

export interface Website {
  name: string;
  description: string;
  slug: string;
  imageSrc: string;
  imageAlt: string;
  imagesDesk: ImageSrc[];
  imagesMob: ImageSrc[];
  stack: string[];
  repo: string;
  contribution: string;
  website: string;
  type: "School project" | "LIA project" | "Hobby" | "Master thesis";
  collab: string[];
  focus: string[];
  date: string;
  imagesAdmin?: ImageSrc[];
}

export const features: Website[] = [
  {
    name: "Boilerplate E-Commerce",
    description:
      "Ongoing group project for Wallmander & Co. The plan is to set up a fully functional sandbox e-commerce site with different integrations.",
    slug: getSlug("Boilerplate E-Commerce"),
    imageSrc: "/wall-desk-1.webp",
    imageAlt: "picture",
    imagesDesk: [
      { src: "wall-desk-1.webp", alt: "wall-desk-1.webp" },
      { src: "wall-desk-2.webp", alt: "wall-desk-2.webp" },
      { src: "wall-desk-3.webp", alt: "wall-desk-3.webp" },
      { src: "wall-desk-4.webp", alt: "wall-desk-4.webp" },
    ],
    imagesMob: [],
    stack: [
      "Next.js",
      "Typescript",
      "BigCommerce",
      "Tailwind UI",
      "GraphQL",
      "Clerk",
    ],
    repo: "",
    contribution: "",
    website: "",
    type: "LIA project",
    collab: [],
    focus: [
      "Integration BigCommerce",
      "Customization of Tailwind UI Components",
      "Filtering products",
      "will be continued...",
    ],
    date: "On going",
  },
  {
    name: "MakeUpByS E-Commerce",
    description: "Master Thesis",
    slug: getSlug("MakeUpByS E-Commerce"),
    imageSrc: "/make-desk-1.webp",
    imageAlt: "picture",
    imagesDesk: [
      { src: "make-desk-1.webp", alt: "make-desk-1.webp" },
      { src: "make-desk-2.webp", alt: "make-desk-2.webp" },
      { src: "make-desk-3.webp", alt: "make-desk-3.webp" },
      { src: "make-desk-4.webp", alt: "make-desk-4.webp" },
    ],
    imagesMob: [
      { src: "make-mob-1.webp", alt: "make-mob-1.webp" },
      { src: "make-mob-2.webp", alt: "make-mob-2.webp" },
      { src: "make-mob-3.webp", alt: "make-mob-3.webp" },
      { src: "make-mob-4.webp", alt: "make-mob-4.webp" },
    ],
    imagesAdmin: [
      { src: "admin-1.webp", alt: "admin-1.webp" },
      { src: "admin-2.webp", alt: "admin-2.webp" },
      { src: "admin-3.webp", alt: "admin-3.webp" },
      { src: "admin-4.webp", alt: "admin-4.webp" },
      { src: "admin-5.webp", alt: "admin-5.webp" },
      { src: "admin-6.webp", alt: "admin-6.webp" },
      { src: "admin-7.webp", alt: "admin-7.webp" },
      { src: "admin-8.webp", alt: "admin-8.webp" },
      { src: "admin-9.webp", alt: "admin-9.webp" },
      { src: "admin-10.webp", alt: "admin-10.webp" },
      { src: "admin-11.webp", alt: "admin-11.webp" },
    ],
    stack: ["Next.js", "Typescript", "Mantine UI", "MongoDB"],
    repo: "https://github.com/totaldekadens/MakeupByS",
    contribution:
      "https://github.com/totaldekadens/MakeupByS/graphs/contributors",
    website: "https://makeupbys.se/",
    type: "Master thesis",
    collab: ["Jacob Hoggen"],
    focus: [
      "Database",
      "API",
      "Admin page",
      "Quiz",
      "Season and Category page",
      "Product page",
      "Checkout",
      "Cart",
      "Search function",
    ],
    date: "2023-02-01",
  },
  {
    name: "Portfolio",
    description: "Group project done with focus on working with agile methods",
    slug: getSlug("Portfolio"),
    imageSrc: "/port-desk-1.webp",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    imagesDesk: [
      { src: "port-desk-1.webp", alt: "port-desk-1" },
      { src: "port-desk-2.webp", alt: "port-desk-2" },
      { src: "port-desk-3.webp", alt: "port-desk-3" },
      { src: "port-desk-4.webp", alt: "port-desk-4" },
    ],
    imagesMob: [
      { src: "port-mob-1.webp", alt: "port-mob-1" },
      { src: "port-mob-2.webp", alt: "port-mob-2" },
      { src: "port-mob-3.webp", alt: "port-mob-3" },
      { src: "port-mob-4.webp", alt: "port-mob-4" },
    ],
    stack: ["React.js", "Typescript", "Mantine UI"],
    repo: "https://github.com/totaldekadens/portfolio-assignment",
    contribution:
      "https://github.com/wictoriadrefelt/portfolio-assignment/graphs/contributors",
    website: "",
    type: "School project",
    collab: ["Wictoria Drefeldt", "Hannane Kabuli", "Ali Bami", "Ting Wang"],
    focus: ["Design", "Member page", "Member list page"],
    date: "2022-12-22",
  },

  {
    name: "Business Adventure Hero",
    description:
      "Group project done for H5 Förnyelsebyrå AB with focus on SEO, Accessibilty and capacity",
    slug: getSlug("Business Adventure Hero"),
    imageSrc: "/adv-desk-1-dark.webp",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    imagesDesk: [
      { src: "adv-desk-1-light.webp", alt: "image of website" },
      { src: "adv-desk-2-light.webp", alt: "image of website" },
      { src: "adv-desk-3-light.webp", alt: "image of website" },
      { src: "adv-desk-1-dark.webp", alt: "image of website" },
    ],
    imagesMob: [
      { src: "adv-mob-1-light.webp", alt: "image of website" },
      { src: "adv-mob-1-dark.webp", alt: "image of website" },
    ],
    stack: ["Next.js", "Typescript", "Mantine UI"],
    repo: "",
    contribution: "",
    website: "https://business.adventurehero.se/",
    type: "LIA project",
    collab: ["Millie Cheung", "Hugo Bengtsson"],
    focus: [
      "Header",
      "Dark/Light mode",
      "Different components on price and home page",
    ],
    date: "2022-10-31",
  },
  {
    name: "FortKnox E-Commerce",
    description: "Group project focused on checkout and admin",
    slug: getSlug("FortKnox E-Commerce"),
    imageSrc: "/fort-desk-1.webp",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    imagesDesk: [
      { src: "fort-desk-1.webp", alt: "image of website" },
      { src: "fort-desk-2.webp", alt: "image of website" },
      { src: "fort-desk-3.webp", alt: "image of website" },
      { src: "fort-desk-4.webp", alt: "image of website" },
      { src: "fort-desk-5.webp", alt: "image of website" },
      { src: "fort-desk-6.webp", alt: "image of website" },
      { src: "fort-desk-7.webp", alt: "image of website" },
      { src: "fort-desk-8.webp", alt: "image of website" },
      { src: "fort-desk-9.webp", alt: "image of website" },
      { src: "fort-desk-10.webp", alt: "image of website" },
      { src: "fort-desk-11.webp", alt: "image of website" },
      { src: "fort-desk-12.webp", alt: "image of website" },
      { src: "fort-desk-13.webp", alt: "image of website" },
      { src: "fort-desk-14.webp", alt: "image of website" },
      { src: "fort-desk-15.webp", alt: "image of website" },
    ],
    imagesMob: [
      { src: "fort-mob-1.webp", alt: "image of website" },
      { src: "fort-mob-2.webp", alt: "image of website" },
      { src: "fort-mob-3.webp", alt: "image of website" },
      { src: "fort-mob-4.webp", alt: "image of website" },
      { src: "fort-mob-5.webp", alt: "image of website" },
      { src: "fort-mob-6.webp", alt: "image of website" },
      { src: "fort-mob-7.webp", alt: "image of website" },
      { src: "fort-mob-8.webp", alt: "image of website" },
    ],
    stack: ["React.js", "Typescript"],
    repo: "https://github.com/totaldekadens/Fortknox",
    contribution:
      "https://github.com/totaldekadens/Fortknox/graphs/contributors",
    website: "",
    type: "School project",
    collab: ["Hugo Bengtsson", "Fredrik Lexö"],
    focus: [
      "Admin page",
      "Home page",
      "Responsivity product page",
      "Order confirmation",
    ],
    date: "2022-06-13",
  },
  {
    name: "SAD Active E-Commerce",
    description: "Group project focused on creating a child theme",
    slug: getSlug("SAD Active E-Commerce"),
    imageSrc: "/sad-desk-1.webp",
    imagesDesk: [
      { src: "sad-desk-1.webp", alt: "image of website" },
      { src: "sad-desk-2.webp", alt: "image of website" },
      { src: "sad-desk-3.webp", alt: "image of website" },
      { src: "sad-desk-4.webp", alt: "image of website" },
      { src: "sad-desk-5.webp", alt: "image of website" },
      { src: "sad-desk-6.webp", alt: "image of website" },
      { src: "sad-desk-7.webp", alt: "image of website" },
      { src: "sad-desk-8.webp", alt: "image of website" },
      { src: "sad-desk-9.webp", alt: "image of website" },
      { src: "sad-desk-10.webp", alt: "image of website" },
      { src: "sad-desk-11.webp", alt: "image of website" },
      { src: "sad-desk-12.webp", alt: "image of website" },
      { src: "sad-desk-13.webp", alt: "image of website" },
      { src: "sad-desk-14.webp", alt: "image of website" },
      { src: "sad-desk-15.webp", alt: "image of website" },
      { src: "sad-desk-16.webp", alt: "image of website" },
      { src: "sad-desk-17.webp", alt: "image of website" },
      { src: "sad-desk-18.webp", alt: "image of website" },
      { src: "sad-desk-19.webp", alt: "image of website" },
      { src: "sad-desk-20.webp", alt: "image of website" },
      { src: "sad-desk-21.webp", alt: "image of website" },
      { src: "sad-desk-22.webp", alt: "image of website" },
      { src: "sad-desk-23.webp", alt: "image of website" },
      { src: "sad-desk-24.webp", alt: "image of website" },
    ],
    imagesMob: [
      { src: "sad-mob-1.webp", alt: "image of website" },
      { src: "sad-mob-2.webp", alt: "image of website" },
      { src: "sad-mob-3.webp", alt: "image of website" },
      { src: "sad-mob-4.webp", alt: "image of website" },
      { src: "sad-mob-5.webp", alt: "image of website" },
      { src: "sad-mob-6.webp", alt: "image of website" },
      { src: "sad-mob-7.webp", alt: "image of website" },
      { src: "sad-mob-8.webp", alt: "image of website" },
      { src: "sad-mob-9.webp", alt: "image of website" },
      { src: "sad-mob-10.webp", alt: "image of website" },
    ],
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    stack: ["Vanilla JS", "MySQL", "PHP", "Wordpress", "WooCommerce"],
    repo: "https://github.com/totaldekadens/Wordpress---Webshop",
    contribution:
      "https://github.com/totaldekadens/Wordpress---Webshop/graphs/contributors",
    website: "",
    type: "School project",
    collab: ["David Wong", "Sanaz Shahed"],
    focus: [
      "Database",
      "API",
      "Category page",
      "Header",
      "Footer",
      "Blog pages",
      "Part of the checkout",
      "Search function",
    ],
    date: "2022-05-02",
  },
  {
    name: "Zeon Milo E-Commerce",
    description:
      "Group project focused on creating a complete backend and frontend",
    slug: getSlug("Zeon Milo E-Commerce"),
    imageSrc: "/zeon-desk-1.webp",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    imagesDesk: [
      { src: "zeon-desk-1.webp", alt: "image of website" },
      { src: "zeon-desk-2.webp", alt: "image of website" },
      { src: "zeon-desk-3.webp", alt: "image of website" },
      { src: "zeon-desk-4.webp", alt: "image of website" },
      { src: "zeon-desk-5.webp", alt: "image of website" },
      { src: "zeon-desk-6.webp", alt: "image of website" },
      { src: "zeon-desk-7.webp", alt: "image of website" },
      { src: "zeon-desk-8.webp", alt: "image of website" },
      { src: "zeon-desk-9.webp", alt: "image of website" },
      { src: "zeon-desk-10.webp", alt: "image of website" },
    ],
    imagesMob: [
      { src: "zeon-mob-1.webp", alt: "image of website" },
      { src: "zeon-mob-2.webp", alt: "image of website" },
      { src: "zeon-mob-3.webp", alt: "image of website" },
      { src: "zeon-mob-4.webp", alt: "image of website" },
      { src: "zeon-mob-5.webp", alt: "image of website" },
      { src: "zeon-mob-6.webp", alt: "image of website" },
      { src: "zeon-mob-7.webp", alt: "image of website" },
      { src: "zeon-mob-8.webp", alt: "image of website" },
    ],
    stack: ["Vanilla JS", "MySQL", "PHP"],
    repo: "https://github.com/totaldekadens/Webshop",
    contribution: "https://github.com/AminaHallam/Webshop/graphs/contributors",
    website: "",
    type: "School project",
    collab: [
      "Lisa Karnerfors",
      "Amina Hallam",
      "Fredrik Olsson",
      "Wictoria Drefeldt",
    ],
    focus: ["Database", "API", "Category page", "Checkout", "Cart", "Admin"],
    date: "2022-03-03",
  },
  {
    name: "Puzzle",
    description: "Own little puzzle project",
    slug: getSlug("Puzzle"),
    imageSrc: "/puzzle.webp",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    imagesDesk: [{ src: "puzzle.webp", alt: "image of website" }],
    imagesMob: [],
    stack: ["Vanilla JS"],
    repo: "https://github.com/totaldekadens/Puzzle",
    contribution: "",
    website: "https://totaldekadens.github.io/Puzzle/",
    type: "Hobby",
    collab: [],
    focus: ["Practice functions"],
    date: "2022-01-09",
  },
];
