import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
import getSlug from "@/utils/getSlug";
import Hero from "@/components/Hero";
import Presentation from "@/components/Presentation";
import { features } from "@/utils/data";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [hidden, setHidden] = useState<boolean>(true);
  return (
    <>
      <Head>
        <title>Portfolio - Angelica Moberg Skoglund</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main
        style={{ paddingTop: 96 }}
        className="bg-black font-primary flex flex-col items-center"
      >
        <Hero />
        <Presentation />
        <div className="mx-auto max-w-7xl py-8 sm:py-10 px-4 sm:px-10 lg:px-4 lg:py-16 ">
          <div className="mx-auto px-4 lg:max-w-none">
            <div className="max-w-3xl">
              <p className="font-primary mt-2 text-3xl font-semi tracking-tight text-slate-50 sm:text-4xl  lg:text-5xl">
                Projects
              </p>
            </div>

            <div className="mt-10 space-y-18 md:space-y-18 border-t border-gray-200 pt-10 sm:mt-16 sm:pt-16">
              {features.map((feature) => (
                <div
                  key={feature.name}
                  className="font-primary mb-28 sm:mb-36 flex flex-col-reverse lg:grid lg:grid-cols-12 lg:items-center lg:gap-x-8"
                >
                  <div className="mt-6 lg:col-span-5 lg:mt-0 xl:col-span-4">
                    <div className="text-gray-600 text-xs">
                      {"Date: " + feature.date}
                    </div>
                    <Link href={"/" + feature.slug}>
                      <h3 className="text-lg font-medium text-gray-300">
                        {feature.name}
                      </h3>
                    </Link>
                    <p className="mt-2 text-sm text-gray-600">
                      {feature.description}
                    </p>

                    <p className="text-white text-sm font mt-2">Stack/Tech</p>
                    <ul>
                      {feature.stack.map((st, i) => {
                        return (
                          <span
                            key={i}
                            className="mr-1 mt-2 inline-flex items-center rounded-full bg-white px-2.5 py-0.5 text-xs font-medium text-teal-900"
                          >
                            {st}
                          </span>
                        );
                      })}
                      ;
                    </ul>
                  </div>
                  <div className="flex-auto lg:col-span-7 xl:col-span-8">
                    <div className="relative aspect-w-5 aspect-h-3 overflow-hidden rounded-lg bg-black">
                      <div className="gap-2 z-50 opacity-0 hover:opacity-100 flex justify-center items-center hover:bg-black/20 hover:duration-200 ">
                        {!feature.repo ? null : (
                          <Link target="_blank" href={feature.repo}>
                            <button
                              type="button"
                              className="rounded-md bg-white py-2.5 z-50 px-3.5 text-xs sm:text-sm font-semibold text-teal-900 shadow-sm hover:bg-black hover:text-teal-50"
                            >
                              Go to repo
                            </button>
                          </Link>
                        )}
                        {!feature.website ? null : (
                          <Link target="_blank" href={feature.website}>
                            <button
                              type="button"
                              className="rounded-md bg-white py-2.5 z-50 px-3.5 text-xs sm:text-sm  font-semibold text-teal-900 shadow-sm hover:bg-black hover:text-teal-50"
                            >
                              Go to website
                            </button>
                          </Link>
                        )}
                        <Link href={"/" + feature.slug}>
                          <button
                            type="button"
                            className="rounded-md bg-white py-2.5 z-50 px-3.5 text-xs sm:text-sm font-semibold text-teal-900 shadow-sm hover:bg-black hover:text-teal-50"
                          >
                            Details
                          </button>
                        </Link>
                      </div>
                      <img
                        src={feature.imageSrc}
                        alt={feature.imageAlt}
                        className="object-fit object-top "
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
