import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });
const features = [
  {
    name: "Boilerplate E-Commerce",
    description: "Ongoing project for Wallmander & Co",
    imageSrc: "/wall-desk-1.png",
    imageAlt: "picture",
    stack: ["Next.js", "Typescript", "BigCommerce", "Tailwind UI", "GraphQL"],
    repo: "https://github.com/totaldekadens/commerce-nextjs-bigcommerce",
    website: "",
    type: "LIA 2",
    collab: "",
  },
  {
    name: "MakeUpByS - E-Commerce",
    description: "Master Thesis",
    imageSrc: "/make-desk-1.png",
    imageAlt: "picture",
    stack: ["Next.js", "Typescript", "Mantine UI", "MongoDB"],
    repo: "https://github.com/totaldekadens/MakeupByS",
    website: "",
    type: "School",
    collab: ["Jacob Hoggen"],
  },
  {
    name: "Portfolio",
    description: "Group project done with focus on working with agile methods",
    imageSrc: "/port-desk-1.png",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    stack: ["React.js", "Typescript", "Mantine UI"],
    repo: "https://github.com/totaldekadens/portfolio-assignment",
    website: "",
    type: "School",
    collab: ["Wictoria Drefeldt", "Hannane Kabuli", "Ali Bami", "Ting Wang"],
  },

  {
    name: "Business Adventure Hero",
    description:
      "Group project done with focus on SEO, Accessibilty and capacity",
    imageSrc: "/adv-desk-1-dark.png",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    stack: ["Next.js", "Typescript", "Mantine UI"],
    repo: "",
    website: "https://business.adventurehero.se/",
    type: "LIA 1",
    collab: ["Millie Cheung", "Hugo Bengtsson"],
  },
  {
    name: "FortKnox - E-Commerce",
    description: "Group project",
    imageSrc: "/fort-desk-1.jpeg",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    stack: ["React.js", "Typescript"],
    repo: "https://github.com/totaldekadens/Fortknox",
    website: "",
    type: "School",
    collab: ["Hugo Bengtsson", "Fredrik Lexö"],
  },
  {
    name: "SAD Active E-Commerce",
    description: "Group project",
    imageSrc: "/sad-desk-1.jpeg",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    stack: ["Vanilla JS", "MySQL", "PHP", "Wordpress", "WooCommerce"],
    repo: "https://github.com/totaldekadens/Wordpress---Webshop",
    website: "",
    type: "School",
    collab: ["David Wong", "Sanaz Shahed"],
  },
  {
    name: "Zeon Milo E-Commerce",
    description: "Group project",
    imageSrc: "/zeon-desk-1.jpeg",
    imageAlt: "Black canvas body with chrome zipper and key ring.",
    stack: ["Vanilla JS", "MySQL", "PHP"],
    repo: "https://github.com/totaldekadens/Webshop",
    website: "",
    type: "School",
    collab: [
      "Lisa Karnerfors",
      "Amina Hallam",
      "Fredrik Olsson",
      "Wictoria Drefeldt",
    ],
  },
];

export default function Home() {
  const [hidden, setHidden] = useState<boolean>(true);
  return (
    <>
      <Head>
        <title>Portfolio - Angelica Moberg Skoglund</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main className="bg-black font-primary ">
        <div className="mx-auto max-w-7xl py-24 sm:py-32 sm:px-2 lg:px-4">
          <div className="mx-auto max-w-2xl px-4 lg:max-w-none">
            <div className="max-w-3xl">
              <h2 className="font-primary font-semibold text-slate-400/50">
                Angelica Moberg Skoglund
              </h2>
              <p className="font-primary mt-2 text-3xl font-bold tracking-tight text-slate-50 sm:text-9xl">
                Portfolio
              </p>
              <p className="mt-4 text-slate-50">
                {/*  The Drawstring Canister comes with multiple strap and handle
                options to adapt throughout your day. Shoulder sling it,
                backpack it, or handy carry it. */}
              </p>
            </div>

            <div className="mt-10 space-y-16 border-t border-gray-200 pt-10 sm:mt-16 sm:pt-16">
              {features.map((feature) => (
                <div
                  key={feature.name}
                  className="font-primary flex flex-col-reverse lg:grid lg:grid-cols-12 lg:items-center lg:gap-x-8"
                >
                  <div className="mt-6 lg:col-span-5 lg:mt-0 xl:col-span-4">
                    <h3 className="text-lg font-medium text-gray-400">
                      {feature.name}
                    </h3>
                    <p className="mt-2 text-sm text-gray-600">
                      {feature.description}
                    </p>

                    <p className="text-white text-sm font-bold mt-2">
                      Stack/Tech
                    </p>
                    <ul>
                      {feature.stack.map((st, i) => {
                        return (
                          <span
                            key={i}
                            className="mr-1 mt-2 inline-flex items-center rounded-full bg-indigo-100 px-2.5 py-0.5 text-xs font-medium text-indigo-800"
                          >
                            {st}
                          </span>
                        );
                      })}
                      ;
                    </ul>
                  </div>
                  <div className="flex-auto lg:col-span-7 xl:col-span-8">
                    <div className="relative aspect-w-5 aspect-h-3 overflow-hidden rounded-lg bg-black">
                      <div className="gap-2 z-50 opacity-0 hover:opacity-100 flex justify-center items-center hover:bg-black/20 hover:duration-200">
                        <button
                          type="button"
                          className="rounded-md bg-indigo-50 py-2.5 z-50 px-3.5 text-sm font-semibold text-indigo-600 shadow-sm hover:bg-indigo-100"
                        >
                          Go to repository
                        </button>
                        <button
                          type="button"
                          className="rounded-md bg-indigo-50 py-2.5 z-50 px-3.5 text-sm font-semibold text-indigo-600 shadow-sm hover:bg-indigo-100"
                        >
                          Details
                        </button>
                      </div>
                      <img
                        src={feature.imageSrc}
                        alt={feature.imageAlt}
                        className="object-fit object-top "
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
